

// Auto-generated by scripts/generate-environment.js from .env — do not edit directly.
export const environment = {
  googleScriptUrl: 'https://script.google.com/macros/s/AKfycbw00vPb--PYRD9VIfBFIjNaWGKO3tQFTLRozDHlaM4NEDp6o10sjTuISCd_JlolV9or/exec'
};


